# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(684, 341)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.strategyNameEdit = QtWidgets.QTextEdit(parent=self.groupBox)
        self.strategyNameEdit.setObjectName("strategyNameEdit")
        self.gridLayout.addWidget(self.strategyNameEdit, 1, 0, 1, 1)
        self.strategyOverviewEdit = QtWidgets.QTextEdit(parent=self.groupBox)
        self.strategyOverviewEdit.setObjectName("strategyOverviewEdit")
        self.gridLayout.addWidget(self.strategyOverviewEdit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 1, 1, 1)
        self.strategySetup1 = QtWidgets.QTextEdit(parent=self.groupBox)
        self.strategySetup1.setObjectName("strategySetup1")
        self.gridLayout.addWidget(self.strategySetup1, 3, 0, 1, 1)
        self.strategySetup2 = QtWidgets.QTextEdit(parent=self.groupBox)
        self.strategySetup2.setObjectName("strategySetup2")
        self.gridLayout.addWidget(self.strategySetup2, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 1, 1, 1)
        self.strategySetup3 = QtWidgets.QTextEdit(parent=self.groupBox)
        self.strategySetup3.setObjectName("strategySetup3")
        self.gridLayout.addWidget(self.strategySetup3, 5, 0, 1, 1)
        self.strategySetup4 = QtWidgets.QTextEdit(parent=self.groupBox)
        self.strategySetup4.setObjectName("strategySetup4")
        self.gridLayout.addWidget(self.strategySetup4, 5, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Strategy Setup"))
        self.label.setText(_translate("Dialog", "Strategy Name"))
        self.label_2.setText(_translate("Dialog", "Strategy Overview"))
        self.label_3.setText(_translate("Dialog", "Strategy Setup Step 1"))
        self.label_4.setText(_translate("Dialog", "Strategy Setup Step 2"))
        self.label_5.setText(_translate("Dialog", "Strategy Setup Step 3"))
        self.label_6.setText(_translate("Dialog", "Strategy Setup Step 4"))
