# Form implementation generated from reading ui file 'removeStrategyDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogRemoveStrategy(object):
    def setupUi(self, DialogRemoveStrategy):
        DialogRemoveStrategy.setObjectName("DialogRemoveStrategy")
        DialogRemoveStrategy.resize(400, 130)
        self.groupBox = QtWidgets.QGroupBox(parent=DialogRemoveStrategy)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 101))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxRemove = QtWidgets.QComboBox(parent=self.groupBox)
        self.comboBoxRemove.setEditable(False)
        self.comboBoxRemove.setObjectName("comboBoxRemove")
        self.horizontalLayout.addWidget(self.comboBoxRemove)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.groupBox)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonBox)

        self.retranslateUi(DialogRemoveStrategy)
        self.buttonBox.accepted.connect(DialogRemoveStrategy.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogRemoveStrategy.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogRemoveStrategy)

    def retranslateUi(self, DialogRemoveStrategy):
        _translate = QtCore.QCoreApplication.translate
        DialogRemoveStrategy.setWindowTitle(_translate("DialogRemoveStrategy", "Dialog"))
        self.groupBox.setTitle(_translate("DialogRemoveStrategy", "Remove Strategy"))
        self.label.setText(_translate("DialogRemoveStrategy", "Select strategy"))
        self.comboBoxRemove.setPlaceholderText(_translate("DialogRemoveStrategy", "Select"))
